apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml

secretGenerator:
  - name: random-quotes-secrets
    literals:
      - homepageDisplay="blah dev"


patches:
 - target:
    kind: Ingress
    name: randomquotes-ingress-nginx  
   path: randomquotes-ingress-nginx.yaml