name: Build Container

on:
    push:
      branches: 
        - main
      paths:
          - 'src/**'
          - '.github/**'
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
      paths:
        - 'src/**'
        - '.github/**'
    workflow_dispatch:

jobs:
    build-and-push-application:
        runs-on: ubuntu-latest        
        strategy:
          matrix:
            dotnet-version: ['8.0.x']
        steps:
            - uses: actions/checkout@v1
              with:
                fetch-depth: '0'
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ matrix.dotnet-version }}
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.14
              with:
                  versionSpec: 5.x
            - id: determine_version
              name: Determine Version
              uses: gittools/actions/gitversion/execute@v0.9.14
              with:
                  additionalArguments: /overrideconfig mode=Mainline
          
            - name: Azure Login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
          
            - name: ACR Login
              run: az acr login --name mallfordacr

            - name: build and push website container
              working-directory: src
              run: |
                docker build -f "./RandomQuotes.Web/Dockerfile" -t ${{ secrets.ACR_LOGIN_SERVER }}/randomquotes:${{ env.GitVersion_SemVer }} .
                docker push ${{ secrets.ACR_LOGIN_SERVER }}/randomquotes:${{ env.GitVersion_SemVer }}